[common]
seed = 1
batchsize = 200
batchsize_g = 200

[gaussian]
  n_epochs = 200
  base = "uniform"
  Dz = 10
  Dhs_g = "50,50"
  act = "tanh"
  actlast = "identity"
  norm = false

  [gaussian.gan]
    opt = "adam"
    lr = 1e-4
    beta1 = 5e-1
    Dhs_d = "50,25"

  [gaussian.mmdnet]
    opt = "rmsprop"
    lr = 1e-3
    sigma = "1,2"

  [gaussian.rmmmdnet]
    opt = "adam"
    lr = 1e-3
    beta1 = 5e-1
    sigma = "1,2"
    Dhs_f = "50,25"
    Df = 5

[ring]
  base = "gaussian"
  Dz = 20
  Dhs_g = "100,100"
  act = "relu"
  actlast = "identity"
  norm = false

  [ring.gan]
    n_epochs = 2_000
    opt = "adam"
    lr = 1e-4
    beta1 = 5e-1
    Dhs_d = "100,100"

  [ring.mmdnet]
    n_epochs = 2_000
    opt = "rmsprop"
    lr = 1e-3
    sigma = "1"

  [ring.rmmmdnet]
    n_epochs = 2_000
    opt = "adam"
    lr = 1e-3
    beta1 = 5e-1
    sigma = "1"
    Dhs_f = "100,100"
    Df = 10
    
  [ring.mmdgan]
    n_epochs = 4_000
    opt = "adam"
    lr = 5e-5
    beta1 = 5e-1
    sigma = "1"
    Dhs_f = "100,100"
    Df = 10
    
[3dring]
  base = "gaussian"
  Dz = 20
  Dhs_g = "100,100"
  act = "relu"
  actlast = "identity"
  norm = false
  
  [3dring.rmmmdnet]
    n_epochs = 2_000
    opt = "adam"
    lr = 1e-3
    beta1 = 5e-1
    sigma = "1"
    Dhs_f = "100,100"
    Df = 10

  [3dring.mmdgan]
    n_epochs = 4_000
    opt = "adam"
    lr = 5e-5
    beta1 = 5e-1
    sigma = "1"
    Dhs_f = "100,100"
    Df = 10

[mnist]
  n_epochs = 10
  base = "uniform"
  Dz = 100
  Dhs_g = "200,400,800"
  act = "relu"
  actlast = "sigmoid"
  norm = true

  [mnist.gan]
    opt = "adam"
    lr = 1e-4
    beta1 = 5e-1
    Dhs_d = "400,200"

  [mnist.mmdnet]
    opt = "rmsprop"
    lr = 1e-3
    sigma = "1,5,10"

  [mnist.rmmmdnet]
    opt = "adam"
    lr = 1e-3
    beta1 = 5e-1
    sigma = "0.1,1,10"
    Dhs_f = "conv"
    Df = 100
    
[cifar10]
  n_epochs = 10
  base = "uniform"
  Dz = 150
  Dhs_g = "conv"
  norm = true
  opt = "adam"
  beta1 = 5e-1
  
  [cifar10.gan]
    lr = 1e-4
    Dhs_d = "conv"
    
  [cifar10.mmdnet]
    lr = 1e-3
    sigma = "1,2,4,8,16"
    
  [cifar10.rmmmdnet]
    lr = 2e-4
    sigma = "1,2,4,8,16"
    Dhs_f = "conv"
    Df = 150